In [1]:
import numpy as np

In [2]:
n = [0,1,2,3,4,5,6,7,8]

#### reshape list

In [5]:
n_1 = np.reshape(n, (3,3))
n_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### mean

In [6]:
np.mean(n_1, 0)

array([3., 4., 5.])

In [7]:
np.mean(n_1, 1)

array([1., 4., 7.])

In [8]:
np.mean(n)

4.0

#### variance

In [9]:
np.var(n_1, 0)

array([6., 6., 6.])

In [10]:
np.var(n_1, 1)

array([0.66666667, 0.66666667, 0.66666667])

In [11]:
np.var(n)

6.666666666666667

#### std deviation

In [13]:
np.std(n_1, 0)

array([2.44948974, 2.44948974, 2.44948974])

In [14]:
np.std(n_1, 1)

array([0.81649658, 0.81649658, 0.81649658])

In [15]:
np.std(n)

2.581988897471611

#### max

In [16]:
np.max(n_1, 0)

array([6, 7, 8])

In [17]:
np.max(n_1, 1)

array([2, 5, 8])

In [18]:
np.max(n)

8

#### min

In [19]:
np.min(n_1, 0)

array([0, 1, 2])

In [20]:
np.min(n_1, 1)

array([0, 3, 6])

In [21]:
np.min(n)

0

#### sum

In [22]:
np.sum(n_1, 0)

array([ 9, 12, 15])

In [23]:
np.sum(n_1, 1)

array([ 3, 12, 21])

In [24]:
np.sum(n)

36

In [34]:
def calculate(list):
    if len(list) == 9:
        n_1 = np.reshape(list, (3,3))
        calculations = {}

        calculations["mean"] = [[np.mean(n_1, 0)[i] for i in range(len(np.mean(n_1, 0)))],
                               [np.mean(n_1, 1)[i] for i in range(len(np.mean(n_1, 1)))],
                               np.mean(list)]

        calculations["variance"] = [[np.var(n_1, 0)[i] for i in range(len(np.var(n_1, 0)))],
                               [np.var(n_1, 1)[i] for i in range(len(np.var(n_1, 1)))],
                               np.var(list)]

        calculations["standard deviation"] = [[np.std(n_1, 0)[i] for i in range(len(np.std(n_1, 0)))],
                               [np.std(n_1, 1)[i] for i in range(len(np.std(n_1, 1)))],
                               np.std(list)]

        calculations["max"] = [[np.max(n_1, 0)[i] for i in range(len(np.max(n_1, 0)))],
                               [np.max(n_1, 1)[i] for i in range(len(np.max(n_1, 1)))],
                               np.max(list)]

        calculations["min"] = [[np.min(n_1, 0)[i] for i in range(len(np.min(n_1, 0)))],
                               [np.min(n_1, 1)[i] for i in range(len(np.min(n_1, 1)))],
                               np.min(list)]

        calculations["sum"] = [[np.sum(n_1, 0)[i] for i in range(len(np.sum(n_1, 0)))],
                               [np.sum(n_1, 1)[i] for i in range(len(np.sum(n_1, 1)))],
                               np.sum(list)]
        return calculations
        
        
    else:
        raise ValueError("List must contain nine numbers.")
        
        

        
# calculate([0,1,2,3,4,5,6,7,8])
calculate([2,6,2,8,4,0,1,5,7])
# calculate([9,1,5,3,3,3,2,9,0])
# calculate([2,6,2,8,4,0,1,])

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}